kind: PersistentVolume
apiVersion: v1
metadata:
  name: consul-2-pv
  namespace: consul
  labels:
    type: amazonEBS
spec:
  storageClassName: ebs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-0d54f45d3bfbb157e
    fsType: ext4